### ISSUE TITLE
Připomínky k aktuální verzi

### ISSUE THREAD

**Issue by pilarik31** [KarelNakladal/Codediary#1]
Zdravíčko, řekl jsem si, že vám na to kouknu a měl bych pár připomínek:

- `vendor/` se neverzuje, smažte ho prosím.
- `.DS_Store` taky nikoho nezajímá, hoďte ho do `.gitignore` také.
- Upravte si metadata v `composer.json` s ohledem na projekt, [toto](https://github.com/KarelNakladal/Codediary/blob/9e120ce0cc90c193892ee656d404d8318eaf34a6/composer.json#L5-L14) a [toho](https://github.com/KarelNakladal/Codediary/blob/9e120ce0cc90c193892ee656d404d8318eaf34a6/composer.json#L2) nevypadá moc "profi".
- Naučte se formátovat kód, [tohle](https://github.com/KarelNakladal/Codediary/blob/9e120ce0cc90c193892ee656d404d8318eaf34a6/app/Model/PostFacade.php) je fakt hnus. Asi požádám @MartinKokesOSSP a naučím vás používat [php code sniffer](https://github.com/squizlabs/PHP_CodeSniffer)

**Comment by MartinKokesOSSP** [comment]
až na to PSR hotovo
